<?php

/**
 * @file plugins/generic/betterPassword/features/PasswordRequirementsDescription.php
 *
 * Copyright (c) 2021 University of Pittsburgh
 * Distributed under the GNU GPL v2 or later. For full terms see the file docs/COPYING.
 *
 * @class PasswordRequirementsDescription
 *
 * @ingroup plugins_generic_betterPassword
 *
 * @brief Renders the full list of active password requirements next to the
 *        password input on every form that lets a user set a password.
 */

namespace APP\plugins\generic\betterPassword\features;

use APP\core\Application;
use APP\plugins\generic\betterPassword\BetterPasswordPlugin;
use APP\template\TemplateManager;
use PKP\core\PKPApplication;
use PKP\plugins\Hook;

class PasswordRequirementsDescription
{
    /** HTML class on the injected block — also used as an idempotency marker. */
    private const MARKER_CLASS = 'better-password-requirements';

    /** @var BetterPasswordPlugin */
    private $_plugin;

    /** @var bool Whether the Smarty output filter has been registered this request. */
    private $_filterRegistered = false;

    public function __construct(BetterPasswordPlugin $plugin)
    {
        $this->_plugin = $plugin;

        $hooks = [
            'registrationform::display',
            'changepasswordform::display',
            'loginchangepasswordform::display',
            'resetpasswordform::display',
            'userdetailsform::display',
        ];
        foreach ($hooks as $hook) {
            Hook::add($hook, [$this, 'registerOutputFilter']);
        }
    }

    /**
     * Lazily register the Smarty output filter the first time any of the
     * password-setting forms is being rendered this request.
     */
    public function registerOutputFilter(string $hookName, array $args): bool
    {
        if ($this->_filterRegistered) {
            return false;
        }
        $this->_filterRegistered = true;
        TemplateManager::getManager()->registerFilter('output', [$this, 'inject']);
        return false;
    }

    /**
     * Smarty output filter: prepend the requirements block to the first
     * `name="password"` input it finds. Idempotent within a render via the
     * marker class.
     */
    public function inject(string $output, $smarty): string
    {
        if (str_contains($output, self::MARKER_CLASS)
            || !preg_match('/<input\b[^>]*\bname="password"/', $output)
        ) {
            return $output;
        }

        $items = $this->_buildRequirementItems();
        if (!$items) {
            return $output;
        }

        $listItems = '';
        foreach ($items as $item) {
            $listItems .= '<li>' . htmlspecialchars($item, ENT_QUOTES, 'UTF-8') . '</li>';
        }
        $heading = htmlspecialchars(
            __('plugins.generic.betterPassword.description.requirementsHeading'),
            ENT_QUOTES,
            'UTF-8'
        );

        // Scoped via input-name selectors so the rules apply regardless of
        // where the requirements block sits relative to the password input
        // (inside its wrapper, or as a sibling above it):
        //   1. hide the FBV default sub-label text on the new-password
        //      input, since the requirements list above already covers it.
        //      `:not(.error)` keeps validation errors visible.
        //   2. give the repeat-password input a 24px top margin in stacked
        //      layouts (Change Password tab) so it doesn't touch the field
        //      above it. `:not(.inline)` skips Add User's side-by-side
        //      layout where the two inputs sit on the same row.
        // SecurityRules joins the per-requirement labels with `\n` so they can
        // render on separate lines. The PKP form-error injection HTML-escapes
        // the message before putting it in the DOM, so `<br>` would render
        // literally. `white-space:pre-line` on the error containers preserves
        // the `\n` characters as actual line breaks instead.
        $marker = self::MARKER_CLASS;
        $css = 'input[name="password"] + span > label.sub_label:not(.error){display:none}'
            . '.pkp_helpers_half:not(.inline) input[name="password2"]{margin-top:24px}'
            . 'label.sub_label.error,.notifyFormError .description{white-space:pre-line}';
        $block = '<div class="' . $marker . '">'
            . '<style>' . $css . '</style>'
            . '<p>' . $heading . '</p>'
            . '<ul>' . $listItems . '</ul>'
            . '</div>';

        // Strip the hardcoded leading whitespace inside the error label generated by
        // OJS core templates. This prevents `white-space: pre-line` from turning
        // that template formatting into a visual gap at the top of the red border.
        $output = preg_replace('/(<label[^>]*class="[^"]*\bsub_label error\b[^"]*"[^>]*>)\s+/', '$1', $output);

        // Prepend the block to the whole textInput fragment so it sits as a
        // sibling above the password input's wrapping div, not inside it.
        // Lets the requirements span the full row above side-by-side
        // password/confirm inputs (Add User), and renders identically in
        // the stacked layout (Change Password).
        return $block . $output;
    }

    /**
     * Build the list of human-readable requirement strings reflecting the
     * current site-level plugin settings.
     *
     * @return string[]
     */
    private function _buildRequirementItems(): array
    {
        $contextSite = PKPApplication::CONTEXT_SITE;
        $items = [];

        $minLength = (int) Application::get()->getRequest()->getSite()->getMinPasswordLength();
        if ($minLength > 0) {
            $items[] = __('plugins.generic.betterPassword.requirement.length', ['length' => $minLength]);
        }

        $complexityChecks = [
            'betterPasswordCheckAlpha' => 'plugins.generic.betterPassword.requirement.alpha',
            'betterPasswordCheckNumber' => 'plugins.generic.betterPassword.requirement.number',
            'betterPasswordCheckUppercase' => 'plugins.generic.betterPassword.requirement.uppercase',
            'betterPasswordCheckLowercase' => 'plugins.generic.betterPassword.requirement.lowercase',
            'betterPasswordCheckSpecial' => 'plugins.generic.betterPassword.requirement.special',
        ];
        foreach ($complexityChecks as $setting => $key) {
            if ($this->_plugin->getSetting($contextSite, $setting)) {
                $items[] = __($key);
            }
        }

        if ($this->_plugin->getSetting($contextSite, 'betterPasswordCheckBlacklist')) {
            $items[] = __('plugins.generic.betterPassword.requirement.blocklist');
        }

        $reuseCount = (int) $this->_plugin->getSetting($contextSite, 'betterPasswordInvalidationPasswords');
        if ($reuseCount > 0) {
            $items[] = __('plugins.generic.betterPassword.requirement.noReuse', ['count' => $reuseCount]);
        }

        return $items;
    }
}
